Update .github/workflows/rebaseline-tests.yml (#23803)

diff --git a/.github/workflows/rebaseline-tests.yml b/.github/workflows/rebaseline-tests.yml
--- a/.github/workflows/rebaseline-tests.yml
+++ b/.github/workflows/rebaseline-tests.yml
@@ -39,20 +39,18 @@ jobs:
         run: |
           git config user.name emscripten-bot
           git config user.email emscripten-bot@users.noreply.github.com
-          #echo "TEST" >> README.md
-          #git add README.md
-          #git checkout -b testing ${{ github.ref_name }}
-          #git commit -m "Testing"
           ./bootstrap
-          ./tools/maint/rebaseline_tests.py
+          if ./tools/maint/rebaseline_tests.py; then
+             echo "rebaseline_tests returned zero, expectations up-to-date"
+             exit 0
+          fi
+          code=$?
+          if [[ $code != 2 ]] ; then
+             echo "rebaseline_tests.py failed with unexpected error $code"
+             exit 1
+          fi
       - name: Create PR
-        id: cpr
         run: |
           git push origin testing
           gh pr create --fill --base ${{ github.ref_name }}
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      - name: Enable auto-merge
-        run: gh pr merge --squash --auto "${{ steps.cpr.outputs.pull-request-number }}"
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          gh pr merge --squash --auto
