[CI] Fix rebaseline-tests recipe
Turns out $? doesn't work after the if/else is completed.

diff --git a/.github/workflows/rebaseline-tests.yml b/.github/workflows/rebaseline-tests.yml
--- a/.github/workflows/rebaseline-tests.yml
+++ b/.github/workflows/rebaseline-tests.yml
@@ -44,11 +44,12 @@ jobs:
              echo "rebaseline_tests returned zero, expectations up-to-date"
              # Exit early and don't create a PR
              exit 0
-          fi
-          code=$?
-          if [[ $code != 2 ]] ; then
-             echo "rebaseline_tests.py failed with unexpected error $code"
-             exit 1
+          else
+            code=$?
+            if [[ $code != 2 ]] ; then
+               echo "rebaseline_tests.py failed with unexpected error $code (expected 2)"
+               exit 1
+            fi
           fi
           git push origin testing
           gh pr create --fill --base ${{ github.ref_name }}
